TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devIPCMini.db
DB += $(TOP)/IPCMiniSup/devIPCMini.proto

#=======================================
include $(TOP)/configure/RULES
